
   CREATE TABLE "N01335459"."STOREPRODUCT" 
   (	"SERIALNUMBER" VARCHAR2(20 BYTE), 
	"PRODUCTNAME" VARCHAR2(50 BYTE), 
	"PRODUCINGDATE" DATE, 
	"PURCHASEDATE" DATE DEFAULT sysdate, 
	"COST" NUMBER(10,2), 
	"RETAIL" NUMBER(10,2), 
	"QUANTITY" VARCHAR2(20 BYTE), 
	"AISLE" VARCHAR2(20 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(200 BYTE)
   )
   
  ALTER TABLE STOREPRODUCT ADD CONSTRAINT "PRODUCT_ID_PK" PRIMARY KEY ("SERIALNUMBER");
 
  ALTER TABLE STOREPRODUCT MODIFY ("PURCHASEDATE" NOT NULL ENABLE);
  ALTER TABLE STOREPRODUCT MODIFY ("COST" NOT NULL ENABLE);
  ALTER TABLE STOREPRODUCT MODIFY ("RETAIL" NOT NULL ENABLE);
 
 
  CREATE TABLE STOREINVOICE 
   (	"INVOICEID" NUMBER(10,0), 
	"INVOICEDATE" DATE, 
	"INVOICEPRICE" NUMBER(20,2), 
	"INVOICETAX" NUMBER(20,2), 
	"TOTALINVOICPRICE" NUMBER(20,2)
   )
    ALTER TABLE STOREINVOICE ADD CONSTRAINT "STOREINVOICE_PK" PRIMARY KEY ("INVOICEID");
      CREATE TABLE STOREINVOICEDETAILS 
   (	"INVOICEID" NUMBER(10,0), 
	"SERIALNUMBER" VARCHAR2(20 BYTE), 
	"UNITPRICE" NUMBER(10,2), 
	"QUANTITY" NUMBER(10,0), 
	"DISCOUNT" NUMBER(10,2), 
	"TOTALITEMTAX" NUMBER(10,2), 
	"TOTALITEMPRICE" NUMBER(20,2), 
	"NETPRICE" NUMBER(20,2)
   )
   
   ALTER TABLE STOREINVOICEDETAILS MODIFY ("INVOICEID" NOT NULL ENABLE);
  ALTER TABLE STOREINVOICEDETAILS MODIFY ("SERIALNUMBER" NOT NULL ENABLE);
  ALTER TABLE STOREINVOICEDETAILS MODIFY ("QUANTITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table STOREINVOICEDETAILS
--------------------------------------------------------

  ALTER TABLE STOREINVOICEDETAILS ADD CONSTRAINT "STOREINVOICEDETAILS_INVOICEID_FK" FOREIGN KEY ("INVOICEID")
	  REFERENCES STOREINVOICE ("INVOICEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE STOREINVOICEDETAILS ADD CONSTRAINT "STOREINVOICEDETAILS_SERIALNUMBER_FK" FOREIGN KEY ("SERIALNUMBER")
	  REFERENCES STOREPRODUCT ("SERIALNUMBER") ENABLE;
      
      CREATE TABLE STOREORDER 
   (	"ORDERID" NUMBER(10,0)
   )
   
     ALTER TABLE STOREORDER ADD CONSTRAINT "STOREORDER_PK" PRIMARY KEY ("ORDERID");
     
      CREATE TABLE STOREORDERITEM
   (	"ORDERID" NUMBER(10,0), 
	"ITEMID" NUMBER(10,0), 
	"SERIALNUMBER" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER(10,0)
   )
   
     ALTER TABLE STOREORDERITEM MODIFY ("ORDERID" NOT NULL ENABLE);
  ALTER TABLE STOREORDERITEM MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE STOREORDERITEM MODIFY ("SERIALNUMBER" NOT NULL ENABLE);
  ALTER TABLE STOREORDERITEM MODIFY ("QUANTITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table STOREORDERITEM
--------------------------------------------------------

  ALTER TABLE STOREORDERITEM ADD CONSTRAINT "STOREORDERITEM_ORDERID_FK" FOREIGN KEY ("ORDERID")
	  REFERENCES STOREORDER ("ORDERID") ENABLE;
  ALTER TABLE STOREORDERITEM ADD CONSTRAINT "STOREORDERITEM_SERIALNUMBER_FK" FOREIGN KEY ("SERIALNUMBER")
	  REFERENCES STOREPRODUCT ("SERIALNUMBER") ENABLE;
